version: '2'
services:
  nginxblank:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./site:/site
  phpfpm:
    build: ./fpm
    volumes:
      - ./site:/site
